name: push to mirror repository

on: [push, pull_request]

env:
  MIRROR_REPOSITORY: "EpitechPromo2028/B-MUL-200-LYN-2-1-myrpg-nathan.deleger"
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-MUL-200-LYN-2-1-myrpg-nathan.deleger.git"

jobs:
  repo_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if the repository is the mirror
        run: |
          if [[ "${{ github.repository }}" == "${{ env.MIRROR_REPOSITORY }}" ]]; then
            echo "Test jobs are disabled for the mirror repository"
            exit 1
          fi
  push_to_mirror:
    needs: repo_check
    if: github.event_name == 'push' && steps.repo_check.outputs.run_check == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
